// frontend-react/src/pages/New/index.js
import React, { useState, useMemo } from "react";
import api from "../../services/api";

import camera from "../../assets/camera.svg"

import "./styles.css"

export default function New({ history }) {
    const [thumbnail, setThumbnail] = useState(null);
    const [company, setCompany] = useState("");
    const [techs, setTechs] = useState("");
    const [price, setPrice] = useState("");

    const preview = useMemo(
        () => {
            return thumbnail ? URL.createObjectURL(thumbnail) : null;
        },
        [thumbnail]
    );

    async function handleSubmit(event) {
        event.preventDefault();

        const user_id = localStorage.getItem("user");

        const data = new FormData();
        data.append("thumbnail", thumbnail);
        data.append("company", company);
        data.append("techs", techs);
        data.append("price", price);

        const response = await api.post("/spots", data, {
            headers: { user_id: user_id }
        });

        history.push("/dashboard");
    }


    return (
        <form onSubmit={handleSubmit}>
            <label
                id="thumbnail"
                style={{ backgroundImage: `url(${preview})` }}
                className={thumbnail ? "has-thumbnail" : ""}
            >
                <input type="file" onChange={event => setThumbnail(event.target.files[0])} />
                <img src={camera} alt="Select image" />
            </label>

            <label htmlFor="compay">EMPRESA *</label>
            <input
                id="company"
                placeholder="Sue empresa incrível"
                value={company}
                onChange={event => setCompany(event.target.value)}
            />

            <label htmlFor="techs">TECNOLOGIAS * <span>(separadas por vírgula)</span></label>
            <input
                id="techs"
                placeholder="Quais tecnologias usam?"
                value={techs}
                onChange={event => setTechs(event.target.value)}
            />

            <label htmlFor="techs">VALOR DA DIÁRIA * <span>(em branco para GRATUITO)</span></label>
            <input
                id="price"
                placeholder="Valor cobrado por dia"
                value={price}
                onChange={event => setPrice(event.target.value)}
            />

            <button type="submit" className="btn">Cadastrar</button>
        </form>
    );
}

// frontend-vue/src/pages/New/New.vue
<template>
    <div class="content">
        <form @submit.prevent="handleSubmit">
            <label
                id="thumbnail"
                :style="{ backgroundImage: `url( ${preview} )` }"
                :class="{ 'has-thumbnail' : thumbnail }"
            >

                <input type="file" @change="handleFileInput" required/>
                <img src="../../assets/camera.svg" alt="Select image"/>
            </label>

            <label for="company">EMPRESA *</label>
            <input id="company" placeholder="Sue empresa incrível" required v-model="company" />

            <label for="techs">TECNOLOGIAS * <span>(separadas por vírgula)</span></label>
            <input id="techs" placeholder="Quais tecnologias usam?" required v-model="techs"/>

            <label for="price">VALOR DA DIÁRIA * <span>(em branco para GRATUITO)</span></label>
            <input id="price" placeholder="Valor cobrado por dia" v-model="price"/>

            <button class="btn">Cadastrar</button>
        </form>
    </div>
</template>

<script>
    import api from '@/api';

    export default {
        name: 'New',
        data() {
            return {
                thumbnail: null,
                preview: null,
                company: '',
                techs: '',
                price: ''
            }
        },
        methods: {
            handleFileInput(event) {
                this.thumbnail = event.target.files[0];

                this.thumbnail
                    ? this.preview = URL.createObjectURL(this.thumbnail)
                    : this.preview = null;
            },
            handleSubmit() {
                const user_id = localStorage.getItem("user");

                const data = new FormData();
                data.append("thumbnail", this.thumbnail);
                data.append("company", this.company);
                data.append("techs", this.techs);
                data.append("price", this.price);

                api.post("/spots", data, {
                    headers: {user_id: user_id}
                })
                    .then((r) => {
                        this.$router.push('/dashboard');
                    })
                    .catch((e) => {
                        alert(e.message)
                    });


            }
        }
    }
</script>

<style scoped>
    label#thumbnail {
        margin-bottom: 20px;
        border: 1px dashed #DDD;
        background-size: cover;
        background-position: center;
        cursor: pointer;
        height: 160px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    label#thumbnail input {
        display: none;
    }

    label#thumbnail.has-thumbnail {
        border: 0;
        border-radius: 5px;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, .16), 0 2px 10px 0 rgba(0, 0, 0, .12);
    }

    label#thumbnail.has-thumbnail img {
        display: none;
    }
</style>
