// frontend-react/src/pages/Login/index.js
import React, { useState } from "react";
import api from "../../services/api";

export default function Login({ history }) {
    const [email, setEmail] = useState("");

    async function handleSubmit(event) {
        event.preventDefault();

        const response = await api.post("/sessions", {
            email: email
        });

        const _id = response.data._id;

        localStorage.setItem("user", _id);

        history.push("/dashboard");
    }


    return (
        <>
            <p>
                Ofereça <strong>spots</strong> para programadores e
                encontre <strong>talentos</strong> para sua empresa
            </p>

            <form onSubmit={handleSubmit}>
                <label htmlFor="email">E-MAIL *</label>
                <input
                    id="email"
                    type="email"
                    placeholder="Seu melhor e-mail"
                    onChange={event => setEmail(event.target.value)}
                    value={email}
                />
                <button className="btn" type="submit">Entrar</button>
            </form>
        </>
    );
}

// frontend-vue/src/pages/Login/Login.vue
<template>
    <div class="content">
        <p>
            Ofereça <strong>spots</strong> para programadores e
            encontre <strong>talentos</strong> para sua empresa
        </p>

        <form @submit.prevent="handleSubmit">
            <label for="email">E-MAIL *</label>
            <input id="email" type="email" placeholder="Seu melhor e-mail" required v-model="email"/>
            <button class="btn">Entrar</button>
        </form>
    </div>
</template>

<script>
    import api from '@/api';

    export default {
        name: 'Login',
        data() {
            return {
                email: ""
            }
        },
        methods: {
            handleSubmit() {
                api.post("/sessions", {
                    email: this.email
                }).then((r) => {
                    const _id = r.data._id;
                    localStorage.setItem("user", _id);
                    this.$router.push('/dashboard');

                }).catch((e) => {
                    alert(e.message);

                });
            }
        }
    }
</script>

<style scoped>
    .content p {
        font-size: 22px;
        line-height: 30px;
        margin-bottom: 30px;
    }


</style>
